SEED: 42
num_classes: 608
data_dir: /workspace/DATASETS/tiered-imagenet/tiered_imagenet
batch_size: 256
num_workers: 3
image_size: [84,84]
return_logs: False
eval_every: 5
n_epochs: 100
gpu_id: 1
opt_name: SGD
opt_params:
  lr: !!float 1e-3
  momentum: 0.9
loss: lcacon
loss_params: 
  sim: 'cosine'
  tau: 0.9
  hierarchy_dist_path: src/dataset/hierarchy_pkl
  idx_to_cls_path: src/dataset/hierarchy_pkl/tieredimg_idx_to_cls.pkl
  dataset_name: tiered-imagenet-224

  